language: node_js
node_js:
  - 13

services:
  - docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version 

after_success:
  - echo "done"
